var annotated_dup =
[
    [ "de", "namespacede.html", "namespacede" ],
    [ "NSError(WDUtils)", "category_n_s_error_07_w_d_utils_08.html", "category_n_s_error_07_w_d_utils_08" ],
    [ "WDAddress", "interface_w_d_address.html", "interface_w_d_address" ],
    [ "WDAlipayPayment", "interface_w_d_alipay_payment.html", "interface_w_d_alipay_payment" ],
    [ "WDApplePayManagedPayment", "interface_w_d_apple_pay_managed_payment.html", "interface_w_d_apple_pay_managed_payment" ],
    [ "WDApplePayPayment", "interface_w_d_apple_pay_payment.html", "interface_w_d_apple_pay_payment" ],
    [ "WDBaseStyle", "interface_w_d_base_style.html", "interface_w_d_base_style" ],
    [ "WDCard", "interface_w_d_card.html", "interface_w_d_card" ],
    [ "WDCardField", "interface_w_d_card_field.html", "interface_w_d_card_field" ],
    [ "<WDCardFieldDelegate>", "protocol_w_d_card_field_delegate-p.html", "protocol_w_d_card_field_delegate-p" ],
    [ "WDCardPayment", "interface_w_d_card_payment.html", "interface_w_d_card_payment" ],
    [ "WDCardStyle", "interface_w_d_card_style.html", "interface_w_d_card_style" ],
    [ "WDCardToken", "interface_w_d_card_token.html", "interface_w_d_card_token" ],
    [ "WDClient", "interface_w_d_client.html", "interface_w_d_client" ],
    [ "WDCustomerData", "interface_w_d_customer_data.html", "interface_w_d_customer_data" ],
    [ "WDNativeStyle", "interface_w_d_native_style.html", "interface_w_d_native_style" ],
    [ "WDNotification", "interface_w_d_notification.html", "interface_w_d_notification" ],
    [ "WDOrder", "interface_w_d_order.html", "interface_w_d_order" ],
    [ "WDOrderItem", "interface_w_d_order_item.html", "interface_w_d_order_item" ],
    [ "WDPayment", "interface_w_d_payment.html", "interface_w_d_payment" ],
    [ "WDPaymentResponse", "interface_w_d_payment_response.html", "interface_w_d_payment_response" ],
    [ "WDPayPalPayment", "interface_w_d_pay_pal_payment.html", "interface_w_d_pay_pal_payment" ],
    [ "WDPeriodic", "interface_w_d_periodic.html", "interface_w_d_periodic" ],
    [ "WDSEPAPayment", "interface_w_d_s_e_p_a_payment.html", "interface_w_d_s_e_p_a_payment" ],
    [ "WDSEPAStyle", "interface_w_d_s_e_p_a_style.html", "interface_w_d_s_e_p_a_style" ],
    [ "WDStyle", "interface_w_d_style.html", "interface_w_d_style" ],
    [ "WDSubMerchantInfo", "interface_w_d_sub_merchant_info.html", "interface_w_d_sub_merchant_info" ]
];