var searchData=
[
  ['name',['name',['../interface_w_d_order_item.html#a45b35ddd1c28a87f7e4d4a436659f047',1,'WDOrderItem::name()'],['../classde_1_1wirecard_1_1paymentsdk_1_1models_1_1_order_item.html#ae2582535651e1247cfaff9bc42d8f0f0',1,'de.wirecard.paymentsdk.models.OrderItem.name()']]],
  ['needsdisplayonboundschange',['needsDisplayOnBoundsChange',['https://developer.apple.com/library/ios/#documentation/GraphicsImaging/Reference/CALayer_class/Introduction/Introduction.html#//apple_ref/occ/instp/CALayer/needsDisplayOnBoundsChange',1,'CALayer']]],
  ['new',['new',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/Reference/Reference.html#//apple_ref/occ/clm/NSObject/new',1,'NSObject']]],
  ['newinstance',['newInstance',['../classde_1_1wirecard_1_1paymentsdk_1_1_wirecard_client_builder.html#a7af47df3ab72161495cb1c27a5208c04',1,'de::wirecard::paymentsdk::WirecardClientBuilder']]],
  ['not_5fset',['NOT_SET',['../classde_1_1wirecard_1_1paymentsdk_1_1models_1_1_payment_page_style.html#a1283249c863730ddc19e1287856536d3',1,'de::wirecard::paymentsdk::models::PaymentPageStyle']]],
  ['notification',['Notification',['../classde_1_1wirecard_1_1paymentsdk_1_1models_1_1_notification.html',1,'de::wirecard::paymentsdk::models']]],
  ['notification',['Notification',['../classde_1_1wirecard_1_1paymentsdk_1_1models_1_1_notification.html#a841139ebb76c02d7587725950f722e94',1,'de.wirecard.paymentsdk.models.Notification.Notification(WirecardTransactionState transactionState, String url)'],['../classde_1_1wirecard_1_1paymentsdk_1_1models_1_1_notification.html#a79085b14d6c4dc7b085d645b7c58faa4',1,'de.wirecard.paymentsdk.models.Notification.Notification()']]],
  ['notification_2ejava',['Notification.java',['../_notification_8java.html',1,'']]],
  ['notificationforstate_3a',['notificationForState:',['../interface_w_d_payment.html#ad104470b34d6cd95e37b900675d7246c',1,'WDPayment']]],
  ['notifications',['notifications',['../interface_w_d_payment.html#a072be1b4e7e6c4cc2045fad0a5efaa9b',1,'WDPayment::notifications()'],['../classde_1_1wirecard_1_1paymentsdk_1_1models_1_1_wirecard_payment.html#a40e4f5a3debe254778afd22792096ecc',1,'de.wirecard.paymentsdk.models.WirecardPayment.notifications()']]],
  ['ns_5funavailable',['NS_UNAVAILABLE',['../interface_w_d_client.html#a4c2a11e4d8b7b5dc7b2098c72529dc09',1,'WDClient::NS_UNAVAILABLE()'],['../interface_w_d_payment.html#ad1cdc3a445cb0a3e26d6a8d755316c35',1,'WDPayment::NS_UNAVAILABLE()']]],
  ['nsarray',['NSArray',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/NSArray.html',1,'']]],
  ['nsarray_3c_20wdnotification_20_2a_20_3e',['NSArray&lt; WDNotification * &gt;',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/NSArray.html',1,'']]],
  ['nsarray_3c_20wdorderitem_20_2a_20_3e',['NSArray&lt; WDOrderItem * &gt;',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/NSArray.html',1,'']]],
  ['nsattributedstring',['NSAttributedString',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSAttributedString_Class/Reference/NSAttributedString.html',1,'']]],
  ['nsattributedstring_20uikit_20additions_20reference',['NSAttributedString UIKit Additions Reference',['https://developer.apple.com/library/ios/#documentation/UIKit/reference/NSAttributedString_UIKit_Additions/Reference/Reference.html.html',1,'']]],
  ['nscalendar',['NSCalendar',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSCalendar_Class/Reference/NSCalendar.html',1,'']]],
  ['nscalendar_20class_20reference',['NSCalendar Class Reference',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSCalendar_Class/Reference/NSCalendar.html.html',1,'']]],
  ['nscoder',['NSCoder',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSCoder_Class/Reference/NSCoder.html',1,'']]],
  ['nscoding_2dp',['NSCoding-p',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Protocols/NSCoding_Protocol/Reference/Reference.html',1,'']]],
  ['nscopying_2dp',['NSCopying-p',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Protocols/NSCopying_Protocol/Reference/Reference.html',1,'']]],
  ['nsdata',['NSData',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSData_Class/Reference/Reference.html',1,'']]],
  ['nsdate',['NSDate',['https://developer.apple.com/library/iOS/#documentation/Cocoa/Reference/Foundation/Classes/NSDate_Class/Reference/Reference.html',1,'']]],
  ['nsdateformatter',['NSDateFormatter',['https://developer.apple.com/library/iOS/#documentation/Cocoa/Reference/Foundation/Classes/NSDateFormatter_Class/Reference/Reference.html',1,'']]],
  ['nsdateformatter_20class_20reference',['NSDateFormatter Class Reference',['https://developer.apple.com/library/iOS/#documentation/Cocoa/Reference/Foundation/Classes/NSDateFormatter_Class/Reference/Reference.html.html',1,'']]],
  ['nsdecimalnumber',['NSDecimalNumber',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSDecimalNumber_Class/Reference/Reference.html',1,'']]],
  ['nsdictionary',['NSDictionary',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSDictionary_Class/Reference/Reference.html',1,'']]],
  ['nserror_28wdutils_29',['NSError(WDUtils)',['../category_n_s_error_07_w_d_utils_08.html',1,'']]],
  ['nserror_2bwdutils_2eh',['NSError+WDUtils.h',['../_n_s_error_09_w_d_utils_8h.html',1,'']]],
  ['nsfastenumeration_2dp',['NSFastEnumeration-p',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/NSFastEnumeration_protocol/Reference/NSFastEnumeration.html',1,'']]],
  ['nsformatter',['NSFormatter',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSFormatter_Class/Reference/Reference.html',1,'']]],
  ['nslinebreakbycharwrapping',['NSLineBreakByCharWrapping',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSLineBreakByCharWrapping',1,'NSParagraphStyle']]],
  ['nslinebreakbyclipping',['NSLineBreakByClipping',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSLineBreakByClipping',1,'NSParagraphStyle']]],
  ['nslinebreakbytruncatinghead',['NSLineBreakByTruncatingHead',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSLineBreakByTruncatingHead',1,'NSParagraphStyle']]],
  ['nslinebreakbytruncatingmiddle',['NSLineBreakByTruncatingMiddle',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSLineBreakByTruncatingMiddle',1,'NSParagraphStyle']]],
  ['nslinebreakbytruncatingtail',['NSLineBreakByTruncatingTail',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSLineBreakByTruncatingTail',1,'NSParagraphStyle']]],
  ['nslinebreakbywordwrapping',['NSLineBreakByWordWrapping',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSLineBreakByWordWrapping',1,'NSParagraphStyle']]],
  ['nslinebreakmode',['NSLineBreakMode',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html#//apple_ref/c/tdef/NSLineBreakMode',1,'NSParagraphStyle']]],
  ['nsmutablearray',['NSMutableArray',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSMutableArray_Class/Reference/Reference.html',1,'']]],
  ['nsmutableattributedstring',['NSMutableAttributedString',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSMutableAttributedString_Class/Reference/NSMutableAttributedString.html',1,'']]],
  ['nsmutablecopying_2dp',['NSMutableCopying-p',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Protocols/NSMutableCopying_Protocol/Reference/Reference.html',1,'']]],
  ['nsmutabledata',['NSMutableData',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSMutableData_Class/index.html',1,'']]],
  ['nsmutabledictionary',['NSMutableDictionary',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSMutableDictionary_Class/Reference/Reference.html',1,'']]],
  ['nsmutableset',['NSMutableSet',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSMutableSet_Class/Reference/Reference.html',1,'']]],
  ['nsnull',['NSNull',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSNull_Class/Reference/Reference.html',1,'']]],
  ['nsnumber',['NSNumber',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSNumber_Class/Reference/Reference.html',1,'']]],
  ['nsnumberformatter',['NSNumberFormatter',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSNumberFormatter_Class/Reference/Reference.html#//apple_ref/occ/cl/NSNumberFormatter.html',1,'']]],
  ['nsobject',['NSObject',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/Reference/Reference.html',1,'']]],
  ['nsobject_2dp',['NSObject-p',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Protocols/NSObject_Protocol/Reference/NSObject.html',1,'']]],
  ['nsparagraphstyle',['NSParagraphStyle',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSParagraphStyle_Class/Reference/Reference.html',1,'']]],
  ['nsset',['NSSet',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSSet_Class/Reference/Reference.html',1,'']]],
  ['nsstring',['NSString',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/Reference/NSString.html',1,'']]],
  ['nsvalue',['NSValue',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSValue_Class/Reference/Reference.html',1,'']]],
  ['nsvaluetransformer',['NSValueTransformer',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSValueTransformer_Class/Reference/Reference.html',1,'']]],
  ['null',['null',['https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSNull_Class/Reference/Reference.html#//apple_ref/occ/clm/NSNull/null',1,'NSNull']]],
  ['number',['number',['../interface_w_d_order.html#afbc1afd443e63e78f0380cbd5063d327',1,'WDOrder::number()'],['../classde_1_1wirecard_1_1paymentsdk_1_1models_1_1_order.html#aa64ce45cc287ba5ffdbac998d2560690',1,'de.wirecard.paymentsdk.models.Order.number()']]],
  ['numberplaceholder',['numberPlaceholder',['../interface_w_d_card_field.html#ad30f4eef18582a2ee8fa12ccd195d079',1,'WDCardField']]]
];
